//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Positions = new HashSet<Position>();
        }
    
        public int Id { get; set; }
        public int FirmId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string CustodianCode { get; set; }
        public string Currency { get; set; }
        public Nullable<int> HouseholdId { get; set; }
        public Nullable<int> FeeScheduleId { get; set; }
        public System.DateTime OpenedOn { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastValuedAt { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual FeeSchedule FeeSchedule { get; set; }
        public virtual Firm Firm { get; set; }
        public virtual Household Household { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
    }
}
