//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class FeeBillingEntities : DbContext
    {
        public FeeBillingEntities()
            : base("name=FeeBillingEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<BillingRunQueueItem> BillingRunQueue { get; set; }
        public virtual DbSet<CashFlow> CashFlows { get; set; }
        public virtual DbSet<FeeDebit> FeeDebits { get; set; }
        public virtual DbSet<FeeSchedule> FeeSchedules { get; set; }
        public virtual DbSet<FeeTier> FeeTiers { get; set; }
        public virtual DbSet<FirmBillingExclusion> FirmBillingExclusions { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<Household> Households { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<StagedBatch> StagedBatches { get; set; }
    }
}
