//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeDebit
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public string CustodianCode { get; set; }
        public decimal DebitedAmount { get; set; }
        public System.DateTime DebitedOn { get; set; }
        public string CustodianReference { get; set; }
    }
}
