//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeSchedule()
        {
            this.Accounts = new HashSet<Account>();
            this.Tiers = new HashSet<FeeTier>();
            this.Households = new HashSet<Household>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FirmId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ScheduleType { get; set; }
        public bool IsHousehold { get; set; }
        public decimal MinimumAnnualFee { get; set; }
        public Nullable<decimal> FlatAnnualFee { get; set; }
        public string Currency { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeTier> Tiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Household> Households { get; set; }
    }
}
