//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeTier
    {
        public int Id { get; set; }
        public int FeeScheduleId { get; set; }
        public decimal LowerBound { get; set; }
        public Nullable<decimal> UpperBound { get; set; }
        public decimal AnnualRate { get; set; }
    
        public virtual FeeSchedule FeeSchedule { get; set; }
    }
}
