//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmBillingExclusion
    {
        public int Id { get; set; }
        public int FirmId { get; set; }
        public string SecurityCode { get; set; }
        public string Reason { get; set; }
    }
}
