//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public int RunId { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> HouseholdId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BillingRunQueueItem BillingRun { get; set; }
    }
}
