//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public long Id { get; set; }
        public int AccountId { get; set; }
        public System.DateTime AsOfDate { get; set; }
        public string SecurityCode { get; set; }
        public string SecurityName { get; set; }
        public decimal Quantity { get; set; }
        public decimal MarketValue { get; set; }
        public bool IsCashSleeve { get; set; }
        public Nullable<int> SourceBatchId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
