//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeeBilling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagedBatch
    {
        public int Id { get; set; }
        public string CustodianCode { get; set; }
        public string FileName { get; set; }
        public byte[] Payload { get; set; }
        public string Status { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
    }
}
